book_library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("books.urls")),
]

books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('books_list/', views.books_list, name="book-list"),
    path('random_book/', views.random_book),
    path('randon_book_with_missing/', views.randon_book_with_missing),
    path('custom_path/<str:sub_path_1>/', views.get_path),
    path('books/<int:book_id>/', views.get_book_detail, name="book-detail"),
    path('categories/<slug:category_slug>/books/',
         views.category_books,
         name="category-books"),
]

books/models.py
# Список категорий
from django.db import models

# Create your models here.

# Список категорий
categories_data = [
    {
        'name': 'Python',
        'slug': 'python',
    },
    {
        'name': 'Веб-разработка',
        'slug': 'web-development',
    },
    {
        'name': 'JavaScript',
        'slug': 'javascript',
    },
]

# Список книг
books = [
    {
        'id': 1,
        'title': 'Flask в действии',
        'description': 'Погружение в веб-разработку с использованием Flask.',
        'author': 'Мигель Гринберг',
        'published_year': 2014,
        'category': 'web-development',
    },
    {
        'id': 2,
        'title': 'Django для начинающих',
        'description': 'Изучение веб-разработки с использованием Django.',
        'author': 'Уильям С. Винсент',
        'published_year': 2018,
        'category': 'web-development',
    },
    {
        'id': 3,
        'title': 'Python. Эффективное программирование',
        'description': 'Освоение эффективных практик программирования на Python.',
        'author': 'Бретт Слэткин',
        'published_year': 2015,
        'category': 'python',
    },
    {
        'id': 4,
        'title': 'Fluent Python',
        'description': 'Продвинутое программирование на Python.',
        'author': 'Люсиано Рамалью',
        'published_year': 2015,
        'category': 'python',
    },
    {
        'id': 5,
        'title': 'JavaScript и jQuery: Новые возможности',
        'description': 'Изучение веб-разработки с использованием JavaScript и jQuery.',
        'author': 'Дэвид Сойер Макфарланд',
        'published_year': 2014,
        'category': 'javascript',
    },
    {
        'id': 6,
        'title': 'Python. Тестирование программ',
        'description': 'Практическое руководство по тестированию программ на Python.',
        'author': 'Брайан Окенхейм',
        'published_year': 2014,
        'category': 'python',
    },
    {
        'id': 7,
        'title': 'Flask Web Development',
        'description': 'Developing Web Applications with Python and Flask.',
        'author': 'Miguel Grinberg',
        'published_year': 2014,
        'category': 'web-development',
    },
    {
        'id': 8,
        'title': 'Python Crash Course',
        'description': 'A Hands-On, Project-Based Introduction to Programming.',
        'author': 'Eric Matthes',
        'published_year': 2015,
        'category': 'python',
    },
    {
        'id': 9,
        'title': 'Vue.js в действии',
        'description': 'Разработка современных веб-приложений с использованием Vue.js.',
        'author': 'Эрик Рэндольф',
        'published_year': 2018,
        'category': 'web-development',
    },
    {
        'id': 10,
        'title': 'Effective Python: 90 способов улучшить свой Python код',
        'description': 'Рекомендации по улучшению стиля и эффективности написания Python кода.',
        'author': 'Бретт Слэткин',
        'published_year': 2015,
        'category': 'python',
    },
]

books/views.py
from datetime import datetime
from random import choice, randint

from django.http import HttpResponse, HttpRequest, JsonResponse, Http404
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import books, categories_data


def get_object_or_404(all_books: list, id_: int) -> dict:
    for book in all_books:
        if book["id"] == id_:
            return book

    raise Http404


@login_required()
def index(request: HttpRequest) -> HttpResponse:
    template_name = "index.html"
    context = {
        "books_list": BOOKS,
    }
    return render(request, template_name, context)


def about_handler(request):
    now = datetime.now()
    return HttpResponse(f"Сайт разработан в {now.year}.")


def books_list(request: HttpRequest):
    query_author = request.GET.get("author")
    if query_author:
        books_list = [book for book in books if book['author'] == query_author]
        return JsonResponse(books_list, safe=False, json_dumps_params={"ensure_ascii": False, "indent": 4})

    return JsonResponse(books, safe=False, json_dumps_params={"ensure_ascii": False, "indent": 4})


def random_book(request):
    book = choice(books)
    return JsonResponse(book, json_dumps_params={"ensure_ascii": False, "indent": 4})


def randon_book_with_missing(request):
    id_ = randint(0, 10)
    book = get_object_or_404(books, id_)
    return JsonResponse(book, json_dumps_params={"ensure_ascii": False, "indent": 4})


def get_path(request, sub_path_1):
    return HttpResponse(f"значение")


def get_book_detail(request, book_id: int):
    context = {
        "categories": categories_data,
        "book": get_object_or_404(books, book_id),
    }

    return render(request, "books/book_detail.html", context=context)


def home(request):
    context = {
        "books_list": books,
        "categories": categories_data,
    }
    return render(request, "books/home.html", context=context)


def about(request):
    context = {
        "categories": categories_data,
    }
    return render(request, "books/about.html", context=context)


def category_books(request, category_slug: str):
    category_name = None
    for category in categories_data:
        if category["slug"] == category_slug:
            category_name = category["name"]

    books_list = [book for book in books if book['category'] == category_slug]

    context = {
        "books_list": books_list,
        "categories": categories_data,
        "category_name": category_name,
    }
    return render(request, "books/category_books.html", context=context)

books/templates/books/about.html
{% extends 'base.html' %}

{% block content %}
<h1>О нашей библиотеке</h1>

        <p>Добро пожаловать в библиотеку, посвященную IT литературе! Мы стремимся предоставить широкий спектр книг по программированию, веб-разработке и другим технологическим темам.</p>

        <h2>Наша миссия</h2>
        <p>Мы создали эту библиотеку с целью сделать знания в области информационных технологий доступными для всех. Независимо от вашего уровня опыта, у нас есть книги, которые помогут вам расширить свои знания и умения.</p>

        <h2>Наши категории</h2>
        <p>Мы специализируемся на книгах по языкам программирования, веб-разработке, фреймворкам и смежным темам. У нас есть разделы, посвященные Python, веб-разработке, JavaScript и многим другим областям IT.</p>

        <h2>Как пользоваться библиотекой</h2>
        <p>Просто просматривайте наш каталог книг, выбирайте интересующие вас темы и наслаждайтесь чтением. Мы также регулярно обновляем наш ассортимент, чтобы держать вас в курсе последних тенденций в мире технологий.</p>

        <p>Спасибо, что выбрали нашу библиотеку!</p>
{% endblock %}

books/templates/books/book_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <p class="card-text">{{ book.author }}</p>
            <p class="card-text">{{ book.published_year }}</p>
            <hr>
            <h6>Описание книги:</h6>
            <p class="card-text">{{ book.description }}</p>
        </div>
    </div>
{% endblock %}

books/templates/books/category_books.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>{{ category_name }}</h1>
    <div class="row">
        <!-- Карточка 1 -->
        {% for book_dict in books_list %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ book_dict.title }}</h5>
                        <p class="card-text">{{ book_dict.author }}</p>
                        <p class="card-text">{{ book_dict.published_year }}</p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Книг нет</p>
        {% endfor %}
    </div>
{% endblock %}

books/templates/books/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>Популярные книги</h1>
    <div class="row">
        <!-- Карточка 1 -->
        {% for book_dict in books_list %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ book_dict.title }}</h5>
                        <p class="card-text">{{ book_dict.author }}</p>
                        <p class="card-text">{{ book_dict.published_year }}</p>
                        <a href={% url 'books:book-detail' book_dict.id %}>Подробнее ...</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Книг нет</p>
        {% endfor %}
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Библиотека</title>
    <!-- Подключаем Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Подключаем ваши стили -->
    <link rel="stylesheet" href="{% static 'books/css/styles.css' %}">
</head>
<body>
    {% include 'includes/header.html' %}

    {% include 'includes/nav.html' with categories=categories %}

    <div class="container mt-4">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Подключаем Bootstrap JS (необходим для работы некоторых Bootstrap компонентов) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/includes/header.html
<header>
    <h1>Библиотека</h1>
</header>

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href={% url 'books:home' %}>Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Категории
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in categories %}
                        <a class="dropdown-item" href={% url 'books:category-books' category.slug %}>{{ category.name }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href={% url 'books:about' %}>О библиотеке</a>
            </li>
        </ul>
    </div>
</nav>